Try fixing spurious exception in DisconnectionIntegrationTest
Can't seem to reproduce it locally, happened once on github.
This is a hopeful attempt at fixing it.
Calling SocketClientNetManager#close() caused:
java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.NioSocketImpl.ensureOpenAndConnected(NioSocketImpl.java:163)
	at java.base/sun.nio.ch.NioSocketImpl.beginWrite(NioSocketImpl.java:356)
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:401)
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:433)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:812)
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1120)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1897)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.flush(ObjectOutputStream.java:1842)
	at java.base/java.io.ObjectOutputStream.flush(ObjectOutputStream.java:734)
	at java.base/java.io.ObjectOutputStream.close(ObjectOutputStream.java:756)
	at it.polimi.ingsw.client.network.socket.ClientSocketManagerImpl.close(ClientSocketManagerImpl.java:74)
    at it.polimi.ingsw.client.network.socket.SocketClientNetManager.close(SocketClientNetManager.java:202)